/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#3e4c5c",
        "on-surface-variant": "#444653",
        "primary-container": "#1e40af",
        "on-tertiary-container": "#adbccf",
        "outline-variant": "#c4c5d5",
        "on-secondary-fixed": "#001c39",
        "error-container": "#ffdad6",
        "secondary": "#0060ac",
        "surface-bright": "#f9f9ff",
        "on-secondary-container": "#003c70",
        "inverse-surface": "#2a313d",
        "background": "#f9f9ff",
        "on-primary-fixed": "#001453",
        "on-secondary-fixed-variant": "#004883",
        "outline": "#757684",
        "surface-container": "#e7eefe",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b8c4ff",
        "surface-container-high": "#e2e8f8",
        "primary-fixed": "#dde1ff",
        "surface-dim": "#d3daea",
        "secondary-fixed-dim": "#a4c9ff",
        "on-primary-fixed-variant": "#173bab",
        "surface-container-low": "#f0f3ff",
        "on-primary-container": "#a8b8ff",
        "on-secondary": "#ffffff",
        "tertiary": "#273545",
        "on-tertiary-fixed": "#0e1d2b",
        "surface-variant": "#dce2f3",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#64a8fe",
        "primary": "#00288e",
        "surface-tint": "#3755c3",
        "error": "#ba1a1a",
        "secondary-fixed": "#d4e3ff",
        "tertiary-fixed-dim": "#b9c8db",
        "on-tertiary-fixed-variant": "#3a4858",
        "surface-container-highest": "#dce2f3",
        "on-surface": "#151c27",
        "on-background": "#151c27",
        "on-tertiary": "#ffffff",
        "surface": "#f9f9ff",
        "inverse-primary": "#b8c4ff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "tertiary-fixed": "#d5e4f8"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "32px",
        "md": "16px",
        "container-max": "1280px",
        "base": "4px",
        "2xl": "48px",
        "gutter": "24px",
        "lg": "24px",
        "xs": "4px",
        "sm": "8px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "h2": ["30px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h1": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.04em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
